### ISSUE TITLE
contentInset conflict

### ISSUE THREAD

**Issue by jklundell** [bogardon/MSPullToRefreshController#5]
The code appears to assume that it has exclusive use of the scrollView.contentInset, at least in the relevant direction. I'm not sure what the best solution would be. Observing contentInset might be the beginning of a solution, but the changes to it could confuse the host app (depending on how it was being used), and PTRC would have to deal with observing its own stores to contentInset.

Alternatively, PTRC could act as a proxy for scrollView.contentInset. The host would access it there, and PTRC could calculate the composite inset and send it to scrollView. (I'm armwaving a bit here, but you get the idea.) An app that never sets contentInset could ignore the whole thing, of course.

My app not only sets contentInset, but it can change it as a side effect of a refresh.

**Comment by bogardon** [comment]
Yeah I see the problem here. If the user wants a different default `contentInset`, PTRC would totally screw it.

I could expose a `delegate` methods that allows you to specify where the `contentInset` should go after ending the refresh cycle?

**Comment by bogardon** [comment]
#6 seems to address this a little bit.

**Comment by jklundell** [comment]
I think it does, yes. FWIW, I implemented a hook by which the app asks PTR to set contentInset, and PTR then takes that into account. That approach has an advantage that it works more like the native UIScrollView: you set a contentInset when you want it, and that's the end of it.

BTW, I'm finding that iOS 7 has some really odd (buggy?) behavior associated with contentInset. Not sure it affects PTR, though.

**Comment by bogardon** [comment]
1.1.0 should address this.
